title: Sergio Morales
email: s@serge.dev
description: >
  Software developer with a focus on complex desktop web applications.
baseurl: ""
url: "https://www.sergemorales.com"
twitter_username: sergelerator
github_username:  sergelerator

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

collections:
  topics:
    output: true
